/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TilbakestillPassordRouteImport } from './routes/tilbakestill-passord'
import { Route as MinProfilRouteImport } from './routes/min-profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlemtPassordRouteImport } from './routes/glemt-passord'
import { Route as StyreRouteRouteImport } from './routes/styre/route'
import { Route as NoterRouteRouteImport } from './routes/noter/route'
import { Route as GruppeledereRouteRouteImport } from './routes/gruppeledere/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtstyrIndexRouteImport } from './routes/utstyr/index'
import { Route as StyreIndexRouteImport } from './routes/styre/index'
import { Route as ProsjekterIndexRouteImport } from './routes/prosjekter/index'
import { Route as NoterIndexRouteImport } from './routes/noter/index'
import { Route as MedlemmerIndexRouteImport } from './routes/medlemmer/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as KalenderIndexRouteImport } from './routes/kalender/index'
import { Route as InnstillingerIndexRouteImport } from './routes/innstillinger/index'
import { Route as GruppeledereIndexRouteImport } from './routes/gruppeledere/index'
import { Route as BeskjederIndexRouteImport } from './routes/beskjeder/index'
import { Route as ArkivIndexRouteImport } from './routes/arkiv/index'
import { Route as VTokenRouteImport } from './routes/v/$token'
import { Route as UtstyrAssetIdRouteImport } from './routes/utstyr/$assetId'
import { Route as StyreTaskIdRouteImport } from './routes/styre/$taskId'
import { Route as ProsjekterProjectIdRouteImport } from './routes/prosjekter/$projectId'
import { Route as MediaMediaIdRouteImport } from './routes/media/$mediaId'
import { Route as KalenderEventIdRouteImport } from './routes/kalender/$eventId'
import { Route as InnstillingerNedlastingerRouteImport } from './routes/innstillinger/nedlastinger'
import { Route as BeskjederNyRouteImport } from './routes/beskjeder/ny'
import { Route as ArkivWorkIdRouteImport } from './routes/arkiv/$workId'
import { Route as ApiDevSeedRouteImport } from './routes/api/dev-seed'
import { Route as ApiDevLoginRouteImport } from './routes/api/dev-login'
import { Route as StyreProsjekterIndexRouteImport } from './routes/styre/prosjekter/index'
import { Route as StyreMoterIndexRouteImport } from './routes/styre/moter/index'
import { Route as StyreDokumenterIndexRouteImport } from './routes/styre/dokumenter/index'
import { Route as StyreChatIndexRouteImport } from './routes/styre/chat/index'
import { Route as NoterProsjekterIndexRouteImport } from './routes/noter/prosjekter/index'
import { Route as NoterArkivIndexRouteImport } from './routes/noter/arkiv/index'
import { Route as KalenderSosialtIndexRouteImport } from './routes/kalender/sosialt/index'
import { Route as GruppeledereChatIndexRouteImport } from './routes/gruppeledere/chat/index'
import { Route as BeskjederPostIdIndexRouteImport } from './routes/beskjeder/$postId/index'
import { Route as StyreProsjekterBoardProjectIdRouteImport } from './routes/styre/prosjekter/$boardProjectId'
import { Route as StyreMoterMeetingIdRouteImport } from './routes/styre/moter/$meetingId'
import { Route as NoterProsjekterProjectIdRouteImport } from './routes/noter/prosjekter/$projectId'
import { Route as NoterArkivWorkIdRouteImport } from './routes/noter/arkiv/$workId'
import { Route as KalenderSosialtNyRouteImport } from './routes/kalender/sosialt/ny'
import { Route as BeskjederPostIdRedigerRouteImport } from './routes/beskjeder/$postId/rediger'
import { Route as ApiUtstyrImagesUploadRouteImport } from './routes/api/utstyr-images/upload'
import { Route as ApiUtstyrImagesImageIdRouteImport } from './routes/api/utstyr-images/$imageId'
import { Route as ApiUploadStartRouteImport } from './routes/api/upload/start'
import { Route as ApiUploadPartRouteImport } from './routes/api/upload/part'
import { Route as ApiUploadCompleteRouteImport } from './routes/api/upload/complete'
import { Route as ApiUploadAbortRouteImport } from './routes/api/upload/abort'
import { Route as ApiPostImagesUploadRouteImport } from './routes/api/post-images/upload'
import { Route as ApiPostImagesImageIdRouteImport } from './routes/api/post-images/$imageId'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiMediaMediaIdRouteImport } from './routes/api/media/$mediaId'
import { Route as ApiFilesFileIdRouteImport } from './routes/api/files/$fileId'
import { Route as ApiBoardFilesUploadRouteImport } from './routes/api/board-files/upload'
import { Route as ApiBoardFilesDocumentIdRouteImport } from './routes/api/board-files/$documentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as KalenderSosialtSocialIdIndexRouteImport } from './routes/kalender/sosialt/$socialId/index'
import { Route as NoterProsjekterProjectIdSlagverkRouteImport } from './routes/noter/prosjekter/$projectId_.slagverk'
import { Route as NoterProsjekterProjectIdSceneoppsettRouteImport } from './routes/noter/prosjekter/$projectId_.sceneoppsett'
import { Route as KalenderSosialtSocialIdRedigerRouteImport } from './routes/kalender/sosialt/$socialId/rediger'

const TilbakestillPassordRoute = TilbakestillPassordRouteImport.update({
  id: '/tilbakestill-passord',
  path: '/tilbakestill-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const MinProfilRoute = MinProfilRouteImport.update({
  id: '/min-profil',
  path: '/min-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlemtPassordRoute = GlemtPassordRouteImport.update({
  id: '/glemt-passord',
  path: '/glemt-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const StyreRouteRoute = StyreRouteRouteImport.update({
  id: '/styre',
  path: '/styre',
  getParentRoute: () => rootRouteImport,
} as any)
const NoterRouteRoute = NoterRouteRouteImport.update({
  id: '/noter',
  path: '/noter',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppeledereRouteRoute = GruppeledereRouteRouteImport.update({
  id: '/gruppeledere',
  path: '/gruppeledere',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtstyrIndexRoute = UtstyrIndexRouteImport.update({
  id: '/utstyr/',
  path: '/utstyr/',
  getParentRoute: () => rootRouteImport,
} as any)
const StyreIndexRoute = StyreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StyreRouteRoute,
} as any)
const ProsjekterIndexRoute = ProsjekterIndexRouteImport.update({
  id: '/prosjekter/',
  path: '/prosjekter/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoterIndexRoute = NoterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoterRouteRoute,
} as any)
const MedlemmerIndexRoute = MedlemmerIndexRouteImport.update({
  id: '/medlemmer/',
  path: '/medlemmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderIndexRoute = KalenderIndexRouteImport.update({
  id: '/kalender/',
  path: '/kalender/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnstillingerIndexRoute = InnstillingerIndexRouteImport.update({
  id: '/innstillinger/',
  path: '/innstillinger/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppeledereIndexRoute = GruppeledereIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GruppeledereRouteRoute,
} as any)
const BeskjederIndexRoute = BeskjederIndexRouteImport.update({
  id: '/beskjeder/',
  path: '/beskjeder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivIndexRoute = ArkivIndexRouteImport.update({
  id: '/arkiv/',
  path: '/arkiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UtstyrAssetIdRoute = UtstyrAssetIdRouteImport.update({
  id: '/utstyr/$assetId',
  path: '/utstyr/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const StyreTaskIdRoute = StyreTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => StyreRouteRoute,
} as any)
const ProsjekterProjectIdRoute = ProsjekterProjectIdRouteImport.update({
  id: '/prosjekter/$projectId',
  path: '/prosjekter/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderEventIdRoute = KalenderEventIdRouteImport.update({
  id: '/kalender/$eventId',
  path: '/kalender/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const InnstillingerNedlastingerRoute =
  InnstillingerNedlastingerRouteImport.update({
    id: '/innstillinger/nedlastinger',
    path: '/innstillinger/nedlastinger',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeskjederNyRoute = BeskjederNyRouteImport.update({
  id: '/beskjeder/ny',
  path: '/beskjeder/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivWorkIdRoute = ArkivWorkIdRouteImport.update({
  id: '/arkiv/$workId',
  path: '/arkiv/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSeedRoute = ApiDevSeedRouteImport.update({
  id: '/api/dev-seed',
  path: '/api/dev-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLoginRoute = ApiDevLoginRouteImport.update({
  id: '/api/dev-login',
  path: '/api/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StyreProsjekterIndexRoute = StyreProsjekterIndexRouteImport.update({
  id: '/prosjekter/',
  path: '/prosjekter/',
  getParentRoute: () => StyreRouteRoute,
} as any)
const StyreMoterIndexRoute = StyreMoterIndexRouteImport.update({
  id: '/moter/',
  path: '/moter/',
  getParentRoute: () => StyreRouteRoute,
} as any)
const StyreDokumenterIndexRoute = StyreDokumenterIndexRouteImport.update({
  id: '/dokumenter/',
  path: '/dokumenter/',
  getParentRoute: () => StyreRouteRoute,
} as any)
const StyreChatIndexRoute = StyreChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => StyreRouteRoute,
} as any)
const NoterProsjekterIndexRoute = NoterProsjekterIndexRouteImport.update({
  id: '/prosjekter/',
  path: '/prosjekter/',
  getParentRoute: () => NoterRouteRoute,
} as any)
const NoterArkivIndexRoute = NoterArkivIndexRouteImport.update({
  id: '/arkiv/',
  path: '/arkiv/',
  getParentRoute: () => NoterRouteRoute,
} as any)
const KalenderSosialtIndexRoute = KalenderSosialtIndexRouteImport.update({
  id: '/kalender/sosialt/',
  path: '/kalender/sosialt/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppeledereChatIndexRoute = GruppeledereChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => GruppeledereRouteRoute,
} as any)
const BeskjederPostIdIndexRoute = BeskjederPostIdIndexRouteImport.update({
  id: '/beskjeder/$postId/',
  path: '/beskjeder/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StyreProsjekterBoardProjectIdRoute =
  StyreProsjekterBoardProjectIdRouteImport.update({
    id: '/prosjekter/$boardProjectId',
    path: '/prosjekter/$boardProjectId',
    getParentRoute: () => StyreRouteRoute,
  } as any)
const StyreMoterMeetingIdRoute = StyreMoterMeetingIdRouteImport.update({
  id: '/moter/$meetingId',
  path: '/moter/$meetingId',
  getParentRoute: () => StyreRouteRoute,
} as any)
const NoterProsjekterProjectIdRoute =
  NoterProsjekterProjectIdRouteImport.update({
    id: '/prosjekter/$projectId',
    path: '/prosjekter/$projectId',
    getParentRoute: () => NoterRouteRoute,
  } as any)
const NoterArkivWorkIdRoute = NoterArkivWorkIdRouteImport.update({
  id: '/arkiv/$workId',
  path: '/arkiv/$workId',
  getParentRoute: () => NoterRouteRoute,
} as any)
const KalenderSosialtNyRoute = KalenderSosialtNyRouteImport.update({
  id: '/kalender/sosialt/ny',
  path: '/kalender/sosialt/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const BeskjederPostIdRedigerRoute = BeskjederPostIdRedigerRouteImport.update({
  id: '/beskjeder/$postId/rediger',
  path: '/beskjeder/$postId/rediger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUtstyrImagesUploadRoute = ApiUtstyrImagesUploadRouteImport.update({
  id: '/api/utstyr-images/upload',
  path: '/api/utstyr-images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUtstyrImagesImageIdRoute = ApiUtstyrImagesImageIdRouteImport.update({
  id: '/api/utstyr-images/$imageId',
  path: '/api/utstyr-images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadStartRoute = ApiUploadStartRouteImport.update({
  id: '/api/upload/start',
  path: '/api/upload/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPartRoute = ApiUploadPartRouteImport.update({
  id: '/api/upload/part',
  path: '/api/upload/part',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCompleteRoute = ApiUploadCompleteRouteImport.update({
  id: '/api/upload/complete',
  path: '/api/upload/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadAbortRoute = ApiUploadAbortRouteImport.update({
  id: '/api/upload/abort',
  path: '/api/upload/abort',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostImagesUploadRoute = ApiPostImagesUploadRouteImport.update({
  id: '/api/post-images/upload',
  path: '/api/post-images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostImagesImageIdRoute = ApiPostImagesImageIdRouteImport.update({
  id: '/api/post-images/$imageId',
  path: '/api/post-images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaMediaIdRoute = ApiMediaMediaIdRouteImport.update({
  id: '/api/media/$mediaId',
  path: '/api/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/api/files/$fileId',
  path: '/api/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardFilesUploadRoute = ApiBoardFilesUploadRouteImport.update({
  id: '/api/board-files/upload',
  path: '/api/board-files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardFilesDocumentIdRoute = ApiBoardFilesDocumentIdRouteImport.update({
  id: '/api/board-files/$documentId',
  path: '/api/board-files/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderSosialtSocialIdIndexRoute =
  KalenderSosialtSocialIdIndexRouteImport.update({
    id: '/kalender/sosialt/$socialId/',
    path: '/kalender/sosialt/$socialId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NoterProsjekterProjectIdSlagverkRoute =
  NoterProsjekterProjectIdSlagverkRouteImport.update({
    id: '/prosjekter/$projectId_/slagverk',
    path: '/prosjekter/$projectId/slagverk',
    getParentRoute: () => NoterRouteRoute,
  } as any)
const NoterProsjekterProjectIdSceneoppsettRoute =
  NoterProsjekterProjectIdSceneoppsettRouteImport.update({
    id: '/prosjekter/$projectId_/sceneoppsett',
    path: '/prosjekter/$projectId/sceneoppsett',
    getParentRoute: () => NoterRouteRoute,
  } as any)
const KalenderSosialtSocialIdRedigerRoute =
  KalenderSosialtSocialIdRedigerRouteImport.update({
    id: '/kalender/sosialt/$socialId/rediger',
    path: '/kalender/sosialt/$socialId/rediger',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gruppeledere': typeof GruppeledereRouteRouteWithChildren
  '/noter': typeof NoterRouteRouteWithChildren
  '/styre': typeof StyreRouteRouteWithChildren
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/min-profil': typeof MinProfilRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/beskjeder/ny': typeof BeskjederNyRoute
  '/innstillinger/nedlastinger': typeof InnstillingerNedlastingerRoute
  '/kalender/$eventId': typeof KalenderEventIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/styre/$taskId': typeof StyreTaskIdRoute
  '/utstyr/$assetId': typeof UtstyrAssetIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/beskjeder/': typeof BeskjederIndexRoute
  '/gruppeledere/': typeof GruppeledereIndexRoute
  '/innstillinger/': typeof InnstillingerIndexRoute
  '/kalender/': typeof KalenderIndexRoute
  '/media/': typeof MediaIndexRoute
  '/medlemmer/': typeof MedlemmerIndexRoute
  '/noter/': typeof NoterIndexRoute
  '/prosjekter/': typeof ProsjekterIndexRoute
  '/styre/': typeof StyreIndexRoute
  '/utstyr/': typeof UtstyrIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/board-files/$documentId': typeof ApiBoardFilesDocumentIdRoute
  '/api/board-files/upload': typeof ApiBoardFilesUploadRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/post-images/$imageId': typeof ApiPostImagesImageIdRoute
  '/api/post-images/upload': typeof ApiPostImagesUploadRoute
  '/api/upload/abort': typeof ApiUploadAbortRoute
  '/api/upload/complete': typeof ApiUploadCompleteRoute
  '/api/upload/part': typeof ApiUploadPartRoute
  '/api/upload/start': typeof ApiUploadStartRoute
  '/api/utstyr-images/$imageId': typeof ApiUtstyrImagesImageIdRoute
  '/api/utstyr-images/upload': typeof ApiUtstyrImagesUploadRoute
  '/beskjeder/$postId/rediger': typeof BeskjederPostIdRedigerRoute
  '/kalender/sosialt/ny': typeof KalenderSosialtNyRoute
  '/noter/arkiv/$workId': typeof NoterArkivWorkIdRoute
  '/noter/prosjekter/$projectId': typeof NoterProsjekterProjectIdRoute
  '/styre/moter/$meetingId': typeof StyreMoterMeetingIdRoute
  '/styre/prosjekter/$boardProjectId': typeof StyreProsjekterBoardProjectIdRoute
  '/beskjeder/$postId/': typeof BeskjederPostIdIndexRoute
  '/gruppeledere/chat/': typeof GruppeledereChatIndexRoute
  '/kalender/sosialt/': typeof KalenderSosialtIndexRoute
  '/noter/arkiv/': typeof NoterArkivIndexRoute
  '/noter/prosjekter/': typeof NoterProsjekterIndexRoute
  '/styre/chat/': typeof StyreChatIndexRoute
  '/styre/dokumenter/': typeof StyreDokumenterIndexRoute
  '/styre/moter/': typeof StyreMoterIndexRoute
  '/styre/prosjekter/': typeof StyreProsjekterIndexRoute
  '/kalender/sosialt/$socialId/rediger': typeof KalenderSosialtSocialIdRedigerRoute
  '/noter/prosjekter/$projectId/sceneoppsett': typeof NoterProsjekterProjectIdSceneoppsettRoute
  '/noter/prosjekter/$projectId/slagverk': typeof NoterProsjekterProjectIdSlagverkRoute
  '/kalender/sosialt/$socialId/': typeof KalenderSosialtSocialIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/min-profil': typeof MinProfilRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/beskjeder/ny': typeof BeskjederNyRoute
  '/innstillinger/nedlastinger': typeof InnstillingerNedlastingerRoute
  '/kalender/$eventId': typeof KalenderEventIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/styre/$taskId': typeof StyreTaskIdRoute
  '/utstyr/$assetId': typeof UtstyrAssetIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv': typeof ArkivIndexRoute
  '/beskjeder': typeof BeskjederIndexRoute
  '/gruppeledere': typeof GruppeledereIndexRoute
  '/innstillinger': typeof InnstillingerIndexRoute
  '/kalender': typeof KalenderIndexRoute
  '/media': typeof MediaIndexRoute
  '/medlemmer': typeof MedlemmerIndexRoute
  '/noter': typeof NoterIndexRoute
  '/prosjekter': typeof ProsjekterIndexRoute
  '/styre': typeof StyreIndexRoute
  '/utstyr': typeof UtstyrIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/board-files/$documentId': typeof ApiBoardFilesDocumentIdRoute
  '/api/board-files/upload': typeof ApiBoardFilesUploadRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/post-images/$imageId': typeof ApiPostImagesImageIdRoute
  '/api/post-images/upload': typeof ApiPostImagesUploadRoute
  '/api/upload/abort': typeof ApiUploadAbortRoute
  '/api/upload/complete': typeof ApiUploadCompleteRoute
  '/api/upload/part': typeof ApiUploadPartRoute
  '/api/upload/start': typeof ApiUploadStartRoute
  '/api/utstyr-images/$imageId': typeof ApiUtstyrImagesImageIdRoute
  '/api/utstyr-images/upload': typeof ApiUtstyrImagesUploadRoute
  '/beskjeder/$postId/rediger': typeof BeskjederPostIdRedigerRoute
  '/kalender/sosialt/ny': typeof KalenderSosialtNyRoute
  '/noter/arkiv/$workId': typeof NoterArkivWorkIdRoute
  '/noter/prosjekter/$projectId': typeof NoterProsjekterProjectIdRoute
  '/styre/moter/$meetingId': typeof StyreMoterMeetingIdRoute
  '/styre/prosjekter/$boardProjectId': typeof StyreProsjekterBoardProjectIdRoute
  '/beskjeder/$postId': typeof BeskjederPostIdIndexRoute
  '/gruppeledere/chat': typeof GruppeledereChatIndexRoute
  '/kalender/sosialt': typeof KalenderSosialtIndexRoute
  '/noter/arkiv': typeof NoterArkivIndexRoute
  '/noter/prosjekter': typeof NoterProsjekterIndexRoute
  '/styre/chat': typeof StyreChatIndexRoute
  '/styre/dokumenter': typeof StyreDokumenterIndexRoute
  '/styre/moter': typeof StyreMoterIndexRoute
  '/styre/prosjekter': typeof StyreProsjekterIndexRoute
  '/kalender/sosialt/$socialId/rediger': typeof KalenderSosialtSocialIdRedigerRoute
  '/noter/prosjekter/$projectId/sceneoppsett': typeof NoterProsjekterProjectIdSceneoppsettRoute
  '/noter/prosjekter/$projectId/slagverk': typeof NoterProsjekterProjectIdSlagverkRoute
  '/kalender/sosialt/$socialId': typeof KalenderSosialtSocialIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gruppeledere': typeof GruppeledereRouteRouteWithChildren
  '/noter': typeof NoterRouteRouteWithChildren
  '/styre': typeof StyreRouteRouteWithChildren
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/min-profil': typeof MinProfilRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/beskjeder/ny': typeof BeskjederNyRoute
  '/innstillinger/nedlastinger': typeof InnstillingerNedlastingerRoute
  '/kalender/$eventId': typeof KalenderEventIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/styre/$taskId': typeof StyreTaskIdRoute
  '/utstyr/$assetId': typeof UtstyrAssetIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/beskjeder/': typeof BeskjederIndexRoute
  '/gruppeledere/': typeof GruppeledereIndexRoute
  '/innstillinger/': typeof InnstillingerIndexRoute
  '/kalender/': typeof KalenderIndexRoute
  '/media/': typeof MediaIndexRoute
  '/medlemmer/': typeof MedlemmerIndexRoute
  '/noter/': typeof NoterIndexRoute
  '/prosjekter/': typeof ProsjekterIndexRoute
  '/styre/': typeof StyreIndexRoute
  '/utstyr/': typeof UtstyrIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/board-files/$documentId': typeof ApiBoardFilesDocumentIdRoute
  '/api/board-files/upload': typeof ApiBoardFilesUploadRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/post-images/$imageId': typeof ApiPostImagesImageIdRoute
  '/api/post-images/upload': typeof ApiPostImagesUploadRoute
  '/api/upload/abort': typeof ApiUploadAbortRoute
  '/api/upload/complete': typeof ApiUploadCompleteRoute
  '/api/upload/part': typeof ApiUploadPartRoute
  '/api/upload/start': typeof ApiUploadStartRoute
  '/api/utstyr-images/$imageId': typeof ApiUtstyrImagesImageIdRoute
  '/api/utstyr-images/upload': typeof ApiUtstyrImagesUploadRoute
  '/beskjeder/$postId/rediger': typeof BeskjederPostIdRedigerRoute
  '/kalender/sosialt/ny': typeof KalenderSosialtNyRoute
  '/noter/arkiv/$workId': typeof NoterArkivWorkIdRoute
  '/noter/prosjekter/$projectId': typeof NoterProsjekterProjectIdRoute
  '/styre/moter/$meetingId': typeof StyreMoterMeetingIdRoute
  '/styre/prosjekter/$boardProjectId': typeof StyreProsjekterBoardProjectIdRoute
  '/beskjeder/$postId/': typeof BeskjederPostIdIndexRoute
  '/gruppeledere/chat/': typeof GruppeledereChatIndexRoute
  '/kalender/sosialt/': typeof KalenderSosialtIndexRoute
  '/noter/arkiv/': typeof NoterArkivIndexRoute
  '/noter/prosjekter/': typeof NoterProsjekterIndexRoute
  '/styre/chat/': typeof StyreChatIndexRoute
  '/styre/dokumenter/': typeof StyreDokumenterIndexRoute
  '/styre/moter/': typeof StyreMoterIndexRoute
  '/styre/prosjekter/': typeof StyreProsjekterIndexRoute
  '/kalender/sosialt/$socialId/rediger': typeof KalenderSosialtSocialIdRedigerRoute
  '/noter/prosjekter/$projectId_/sceneoppsett': typeof NoterProsjekterProjectIdSceneoppsettRoute
  '/noter/prosjekter/$projectId_/slagverk': typeof NoterProsjekterProjectIdSlagverkRoute
  '/kalender/sosialt/$socialId/': typeof KalenderSosialtSocialIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gruppeledere'
    | '/noter'
    | '/styre'
    | '/glemt-passord'
    | '/login'
    | '/min-profil'
    | '/tilbakestill-passord'
    | '/api/dev-login'
    | '/api/dev-seed'
    | '/arkiv/$workId'
    | '/beskjeder/ny'
    | '/innstillinger/nedlastinger'
    | '/kalender/$eventId'
    | '/media/$mediaId'
    | '/prosjekter/$projectId'
    | '/styre/$taskId'
    | '/utstyr/$assetId'
    | '/v/$token'
    | '/arkiv/'
    | '/beskjeder/'
    | '/gruppeledere/'
    | '/innstillinger/'
    | '/kalender/'
    | '/media/'
    | '/medlemmer/'
    | '/noter/'
    | '/prosjekter/'
    | '/styre/'
    | '/utstyr/'
    | '/api/auth/$'
    | '/api/board-files/$documentId'
    | '/api/board-files/upload'
    | '/api/files/$fileId'
    | '/api/media/$mediaId'
    | '/api/media/upload'
    | '/api/post-images/$imageId'
    | '/api/post-images/upload'
    | '/api/upload/abort'
    | '/api/upload/complete'
    | '/api/upload/part'
    | '/api/upload/start'
    | '/api/utstyr-images/$imageId'
    | '/api/utstyr-images/upload'
    | '/beskjeder/$postId/rediger'
    | '/kalender/sosialt/ny'
    | '/noter/arkiv/$workId'
    | '/noter/prosjekter/$projectId'
    | '/styre/moter/$meetingId'
    | '/styre/prosjekter/$boardProjectId'
    | '/beskjeder/$postId/'
    | '/gruppeledere/chat/'
    | '/kalender/sosialt/'
    | '/noter/arkiv/'
    | '/noter/prosjekter/'
    | '/styre/chat/'
    | '/styre/dokumenter/'
    | '/styre/moter/'
    | '/styre/prosjekter/'
    | '/kalender/sosialt/$socialId/rediger'
    | '/noter/prosjekter/$projectId/sceneoppsett'
    | '/noter/prosjekter/$projectId/slagverk'
    | '/kalender/sosialt/$socialId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glemt-passord'
    | '/login'
    | '/min-profil'
    | '/tilbakestill-passord'
    | '/api/dev-login'
    | '/api/dev-seed'
    | '/arkiv/$workId'
    | '/beskjeder/ny'
    | '/innstillinger/nedlastinger'
    | '/kalender/$eventId'
    | '/media/$mediaId'
    | '/prosjekter/$projectId'
    | '/styre/$taskId'
    | '/utstyr/$assetId'
    | '/v/$token'
    | '/arkiv'
    | '/beskjeder'
    | '/gruppeledere'
    | '/innstillinger'
    | '/kalender'
    | '/media'
    | '/medlemmer'
    | '/noter'
    | '/prosjekter'
    | '/styre'
    | '/utstyr'
    | '/api/auth/$'
    | '/api/board-files/$documentId'
    | '/api/board-files/upload'
    | '/api/files/$fileId'
    | '/api/media/$mediaId'
    | '/api/media/upload'
    | '/api/post-images/$imageId'
    | '/api/post-images/upload'
    | '/api/upload/abort'
    | '/api/upload/complete'
    | '/api/upload/part'
    | '/api/upload/start'
    | '/api/utstyr-images/$imageId'
    | '/api/utstyr-images/upload'
    | '/beskjeder/$postId/rediger'
    | '/kalender/sosialt/ny'
    | '/noter/arkiv/$workId'
    | '/noter/prosjekter/$projectId'
    | '/styre/moter/$meetingId'
    | '/styre/prosjekter/$boardProjectId'
    | '/beskjeder/$postId'
    | '/gruppeledere/chat'
    | '/kalender/sosialt'
    | '/noter/arkiv'
    | '/noter/prosjekter'
    | '/styre/chat'
    | '/styre/dokumenter'
    | '/styre/moter'
    | '/styre/prosjekter'
    | '/kalender/sosialt/$socialId/rediger'
    | '/noter/prosjekter/$projectId/sceneoppsett'
    | '/noter/prosjekter/$projectId/slagverk'
    | '/kalender/sosialt/$socialId'
  id:
    | '__root__'
    | '/'
    | '/gruppeledere'
    | '/noter'
    | '/styre'
    | '/glemt-passord'
    | '/login'
    | '/min-profil'
    | '/tilbakestill-passord'
    | '/api/dev-login'
    | '/api/dev-seed'
    | '/arkiv/$workId'
    | '/beskjeder/ny'
    | '/innstillinger/nedlastinger'
    | '/kalender/$eventId'
    | '/media/$mediaId'
    | '/prosjekter/$projectId'
    | '/styre/$taskId'
    | '/utstyr/$assetId'
    | '/v/$token'
    | '/arkiv/'
    | '/beskjeder/'
    | '/gruppeledere/'
    | '/innstillinger/'
    | '/kalender/'
    | '/media/'
    | '/medlemmer/'
    | '/noter/'
    | '/prosjekter/'
    | '/styre/'
    | '/utstyr/'
    | '/api/auth/$'
    | '/api/board-files/$documentId'
    | '/api/board-files/upload'
    | '/api/files/$fileId'
    | '/api/media/$mediaId'
    | '/api/media/upload'
    | '/api/post-images/$imageId'
    | '/api/post-images/upload'
    | '/api/upload/abort'
    | '/api/upload/complete'
    | '/api/upload/part'
    | '/api/upload/start'
    | '/api/utstyr-images/$imageId'
    | '/api/utstyr-images/upload'
    | '/beskjeder/$postId/rediger'
    | '/kalender/sosialt/ny'
    | '/noter/arkiv/$workId'
    | '/noter/prosjekter/$projectId'
    | '/styre/moter/$meetingId'
    | '/styre/prosjekter/$boardProjectId'
    | '/beskjeder/$postId/'
    | '/gruppeledere/chat/'
    | '/kalender/sosialt/'
    | '/noter/arkiv/'
    | '/noter/prosjekter/'
    | '/styre/chat/'
    | '/styre/dokumenter/'
    | '/styre/moter/'
    | '/styre/prosjekter/'
    | '/kalender/sosialt/$socialId/rediger'
    | '/noter/prosjekter/$projectId_/sceneoppsett'
    | '/noter/prosjekter/$projectId_/slagverk'
    | '/kalender/sosialt/$socialId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GruppeledereRouteRoute: typeof GruppeledereRouteRouteWithChildren
  NoterRouteRoute: typeof NoterRouteRouteWithChildren
  StyreRouteRoute: typeof StyreRouteRouteWithChildren
  GlemtPassordRoute: typeof GlemtPassordRoute
  LoginRoute: typeof LoginRoute
  MinProfilRoute: typeof MinProfilRoute
  TilbakestillPassordRoute: typeof TilbakestillPassordRoute
  ApiDevLoginRoute: typeof ApiDevLoginRoute
  ApiDevSeedRoute: typeof ApiDevSeedRoute
  ArkivWorkIdRoute: typeof ArkivWorkIdRoute
  BeskjederNyRoute: typeof BeskjederNyRoute
  InnstillingerNedlastingerRoute: typeof InnstillingerNedlastingerRoute
  KalenderEventIdRoute: typeof KalenderEventIdRoute
  MediaMediaIdRoute: typeof MediaMediaIdRoute
  ProsjekterProjectIdRoute: typeof ProsjekterProjectIdRoute
  UtstyrAssetIdRoute: typeof UtstyrAssetIdRoute
  VTokenRoute: typeof VTokenRoute
  ArkivIndexRoute: typeof ArkivIndexRoute
  BeskjederIndexRoute: typeof BeskjederIndexRoute
  InnstillingerIndexRoute: typeof InnstillingerIndexRoute
  KalenderIndexRoute: typeof KalenderIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  MedlemmerIndexRoute: typeof MedlemmerIndexRoute
  ProsjekterIndexRoute: typeof ProsjekterIndexRoute
  UtstyrIndexRoute: typeof UtstyrIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBoardFilesDocumentIdRoute: typeof ApiBoardFilesDocumentIdRoute
  ApiBoardFilesUploadRoute: typeof ApiBoardFilesUploadRoute
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
  ApiMediaMediaIdRoute: typeof ApiMediaMediaIdRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiPostImagesImageIdRoute: typeof ApiPostImagesImageIdRoute
  ApiPostImagesUploadRoute: typeof ApiPostImagesUploadRoute
  ApiUploadAbortRoute: typeof ApiUploadAbortRoute
  ApiUploadCompleteRoute: typeof ApiUploadCompleteRoute
  ApiUploadPartRoute: typeof ApiUploadPartRoute
  ApiUploadStartRoute: typeof ApiUploadStartRoute
  ApiUtstyrImagesImageIdRoute: typeof ApiUtstyrImagesImageIdRoute
  ApiUtstyrImagesUploadRoute: typeof ApiUtstyrImagesUploadRoute
  BeskjederPostIdRedigerRoute: typeof BeskjederPostIdRedigerRoute
  KalenderSosialtNyRoute: typeof KalenderSosialtNyRoute
  BeskjederPostIdIndexRoute: typeof BeskjederPostIdIndexRoute
  KalenderSosialtIndexRoute: typeof KalenderSosialtIndexRoute
  KalenderSosialtSocialIdRedigerRoute: typeof KalenderSosialtSocialIdRedigerRoute
  KalenderSosialtSocialIdIndexRoute: typeof KalenderSosialtSocialIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tilbakestill-passord': {
      id: '/tilbakestill-passord'
      path: '/tilbakestill-passord'
      fullPath: '/tilbakestill-passord'
      preLoaderRoute: typeof TilbakestillPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/min-profil': {
      id: '/min-profil'
      path: '/min-profil'
      fullPath: '/min-profil'
      preLoaderRoute: typeof MinProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glemt-passord': {
      id: '/glemt-passord'
      path: '/glemt-passord'
      fullPath: '/glemt-passord'
      preLoaderRoute: typeof GlemtPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styre': {
      id: '/styre'
      path: '/styre'
      fullPath: '/styre'
      preLoaderRoute: typeof StyreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter': {
      id: '/noter'
      path: '/noter'
      fullPath: '/noter'
      preLoaderRoute: typeof NoterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppeledere': {
      id: '/gruppeledere'
      path: '/gruppeledere'
      fullPath: '/gruppeledere'
      preLoaderRoute: typeof GruppeledereRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utstyr/': {
      id: '/utstyr/'
      path: '/utstyr'
      fullPath: '/utstyr/'
      preLoaderRoute: typeof UtstyrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styre/': {
      id: '/styre/'
      path: '/'
      fullPath: '/styre/'
      preLoaderRoute: typeof StyreIndexRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/prosjekter/': {
      id: '/prosjekter/'
      path: '/prosjekter'
      fullPath: '/prosjekter/'
      preLoaderRoute: typeof ProsjekterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter/': {
      id: '/noter/'
      path: '/'
      fullPath: '/noter/'
      preLoaderRoute: typeof NoterIndexRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/medlemmer/': {
      id: '/medlemmer/'
      path: '/medlemmer'
      fullPath: '/medlemmer/'
      preLoaderRoute: typeof MedlemmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender/': {
      id: '/kalender/'
      path: '/kalender'
      fullPath: '/kalender/'
      preLoaderRoute: typeof KalenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innstillinger/': {
      id: '/innstillinger/'
      path: '/innstillinger'
      fullPath: '/innstillinger/'
      preLoaderRoute: typeof InnstillingerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppeledere/': {
      id: '/gruppeledere/'
      path: '/'
      fullPath: '/gruppeledere/'
      preLoaderRoute: typeof GruppeledereIndexRouteImport
      parentRoute: typeof GruppeledereRouteRoute
    }
    '/beskjeder/': {
      id: '/beskjeder/'
      path: '/beskjeder'
      fullPath: '/beskjeder/'
      preLoaderRoute: typeof BeskjederIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/': {
      id: '/arkiv/'
      path: '/arkiv'
      fullPath: '/arkiv/'
      preLoaderRoute: typeof ArkivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utstyr/$assetId': {
      id: '/utstyr/$assetId'
      path: '/utstyr/$assetId'
      fullPath: '/utstyr/$assetId'
      preLoaderRoute: typeof UtstyrAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styre/$taskId': {
      id: '/styre/$taskId'
      path: '/$taskId'
      fullPath: '/styre/$taskId'
      preLoaderRoute: typeof StyreTaskIdRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/prosjekter/$projectId': {
      id: '/prosjekter/$projectId'
      path: '/prosjekter/$projectId'
      fullPath: '/prosjekter/$projectId'
      preLoaderRoute: typeof ProsjekterProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender/$eventId': {
      id: '/kalender/$eventId'
      path: '/kalender/$eventId'
      fullPath: '/kalender/$eventId'
      preLoaderRoute: typeof KalenderEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innstillinger/nedlastinger': {
      id: '/innstillinger/nedlastinger'
      path: '/innstillinger/nedlastinger'
      fullPath: '/innstillinger/nedlastinger'
      preLoaderRoute: typeof InnstillingerNedlastingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beskjeder/ny': {
      id: '/beskjeder/ny'
      path: '/beskjeder/ny'
      fullPath: '/beskjeder/ny'
      preLoaderRoute: typeof BeskjederNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/$workId': {
      id: '/arkiv/$workId'
      path: '/arkiv/$workId'
      fullPath: '/arkiv/$workId'
      preLoaderRoute: typeof ArkivWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-seed': {
      id: '/api/dev-seed'
      path: '/api/dev-seed'
      fullPath: '/api/dev-seed'
      preLoaderRoute: typeof ApiDevSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-login': {
      id: '/api/dev-login'
      path: '/api/dev-login'
      fullPath: '/api/dev-login'
      preLoaderRoute: typeof ApiDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styre/prosjekter/': {
      id: '/styre/prosjekter/'
      path: '/prosjekter'
      fullPath: '/styre/prosjekter/'
      preLoaderRoute: typeof StyreProsjekterIndexRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/styre/moter/': {
      id: '/styre/moter/'
      path: '/moter'
      fullPath: '/styre/moter/'
      preLoaderRoute: typeof StyreMoterIndexRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/styre/dokumenter/': {
      id: '/styre/dokumenter/'
      path: '/dokumenter'
      fullPath: '/styre/dokumenter/'
      preLoaderRoute: typeof StyreDokumenterIndexRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/styre/chat/': {
      id: '/styre/chat/'
      path: '/chat'
      fullPath: '/styre/chat/'
      preLoaderRoute: typeof StyreChatIndexRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/noter/prosjekter/': {
      id: '/noter/prosjekter/'
      path: '/prosjekter'
      fullPath: '/noter/prosjekter/'
      preLoaderRoute: typeof NoterProsjekterIndexRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/noter/arkiv/': {
      id: '/noter/arkiv/'
      path: '/arkiv'
      fullPath: '/noter/arkiv/'
      preLoaderRoute: typeof NoterArkivIndexRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/kalender/sosialt/': {
      id: '/kalender/sosialt/'
      path: '/kalender/sosialt'
      fullPath: '/kalender/sosialt/'
      preLoaderRoute: typeof KalenderSosialtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppeledere/chat/': {
      id: '/gruppeledere/chat/'
      path: '/chat'
      fullPath: '/gruppeledere/chat/'
      preLoaderRoute: typeof GruppeledereChatIndexRouteImport
      parentRoute: typeof GruppeledereRouteRoute
    }
    '/beskjeder/$postId/': {
      id: '/beskjeder/$postId/'
      path: '/beskjeder/$postId'
      fullPath: '/beskjeder/$postId/'
      preLoaderRoute: typeof BeskjederPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styre/prosjekter/$boardProjectId': {
      id: '/styre/prosjekter/$boardProjectId'
      path: '/prosjekter/$boardProjectId'
      fullPath: '/styre/prosjekter/$boardProjectId'
      preLoaderRoute: typeof StyreProsjekterBoardProjectIdRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/styre/moter/$meetingId': {
      id: '/styre/moter/$meetingId'
      path: '/moter/$meetingId'
      fullPath: '/styre/moter/$meetingId'
      preLoaderRoute: typeof StyreMoterMeetingIdRouteImport
      parentRoute: typeof StyreRouteRoute
    }
    '/noter/prosjekter/$projectId': {
      id: '/noter/prosjekter/$projectId'
      path: '/prosjekter/$projectId'
      fullPath: '/noter/prosjekter/$projectId'
      preLoaderRoute: typeof NoterProsjekterProjectIdRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/noter/arkiv/$workId': {
      id: '/noter/arkiv/$workId'
      path: '/arkiv/$workId'
      fullPath: '/noter/arkiv/$workId'
      preLoaderRoute: typeof NoterArkivWorkIdRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/kalender/sosialt/ny': {
      id: '/kalender/sosialt/ny'
      path: '/kalender/sosialt/ny'
      fullPath: '/kalender/sosialt/ny'
      preLoaderRoute: typeof KalenderSosialtNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beskjeder/$postId/rediger': {
      id: '/beskjeder/$postId/rediger'
      path: '/beskjeder/$postId/rediger'
      fullPath: '/beskjeder/$postId/rediger'
      preLoaderRoute: typeof BeskjederPostIdRedigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/utstyr-images/upload': {
      id: '/api/utstyr-images/upload'
      path: '/api/utstyr-images/upload'
      fullPath: '/api/utstyr-images/upload'
      preLoaderRoute: typeof ApiUtstyrImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/utstyr-images/$imageId': {
      id: '/api/utstyr-images/$imageId'
      path: '/api/utstyr-images/$imageId'
      fullPath: '/api/utstyr-images/$imageId'
      preLoaderRoute: typeof ApiUtstyrImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/start': {
      id: '/api/upload/start'
      path: '/api/upload/start'
      fullPath: '/api/upload/start'
      preLoaderRoute: typeof ApiUploadStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/part': {
      id: '/api/upload/part'
      path: '/api/upload/part'
      fullPath: '/api/upload/part'
      preLoaderRoute: typeof ApiUploadPartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/complete': {
      id: '/api/upload/complete'
      path: '/api/upload/complete'
      fullPath: '/api/upload/complete'
      preLoaderRoute: typeof ApiUploadCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/abort': {
      id: '/api/upload/abort'
      path: '/api/upload/abort'
      fullPath: '/api/upload/abort'
      preLoaderRoute: typeof ApiUploadAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/post-images/upload': {
      id: '/api/post-images/upload'
      path: '/api/post-images/upload'
      fullPath: '/api/post-images/upload'
      preLoaderRoute: typeof ApiPostImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/post-images/$imageId': {
      id: '/api/post-images/$imageId'
      path: '/api/post-images/$imageId'
      fullPath: '/api/post-images/$imageId'
      preLoaderRoute: typeof ApiPostImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId': {
      id: '/api/media/$mediaId'
      path: '/api/media/$mediaId'
      fullPath: '/api/media/$mediaId'
      preLoaderRoute: typeof ApiMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/api/files/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board-files/upload': {
      id: '/api/board-files/upload'
      path: '/api/board-files/upload'
      fullPath: '/api/board-files/upload'
      preLoaderRoute: typeof ApiBoardFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board-files/$documentId': {
      id: '/api/board-files/$documentId'
      path: '/api/board-files/$documentId'
      fullPath: '/api/board-files/$documentId'
      preLoaderRoute: typeof ApiBoardFilesDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender/sosialt/$socialId/': {
      id: '/kalender/sosialt/$socialId/'
      path: '/kalender/sosialt/$socialId'
      fullPath: '/kalender/sosialt/$socialId/'
      preLoaderRoute: typeof KalenderSosialtSocialIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter/prosjekter/$projectId_/slagverk': {
      id: '/noter/prosjekter/$projectId_/slagverk'
      path: '/prosjekter/$projectId/slagverk'
      fullPath: '/noter/prosjekter/$projectId/slagverk'
      preLoaderRoute: typeof NoterProsjekterProjectIdSlagverkRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/noter/prosjekter/$projectId_/sceneoppsett': {
      id: '/noter/prosjekter/$projectId_/sceneoppsett'
      path: '/prosjekter/$projectId/sceneoppsett'
      fullPath: '/noter/prosjekter/$projectId/sceneoppsett'
      preLoaderRoute: typeof NoterProsjekterProjectIdSceneoppsettRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/kalender/sosialt/$socialId/rediger': {
      id: '/kalender/sosialt/$socialId/rediger'
      path: '/kalender/sosialt/$socialId/rediger'
      fullPath: '/kalender/sosialt/$socialId/rediger'
      preLoaderRoute: typeof KalenderSosialtSocialIdRedigerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GruppeledereRouteRouteChildren {
  GruppeledereIndexRoute: typeof GruppeledereIndexRoute
  GruppeledereChatIndexRoute: typeof GruppeledereChatIndexRoute
}

const GruppeledereRouteRouteChildren: GruppeledereRouteRouteChildren = {
  GruppeledereIndexRoute: GruppeledereIndexRoute,
  GruppeledereChatIndexRoute: GruppeledereChatIndexRoute,
}

const GruppeledereRouteRouteWithChildren =
  GruppeledereRouteRoute._addFileChildren(GruppeledereRouteRouteChildren)

interface NoterRouteRouteChildren {
  NoterIndexRoute: typeof NoterIndexRoute
  NoterArkivWorkIdRoute: typeof NoterArkivWorkIdRoute
  NoterProsjekterProjectIdRoute: typeof NoterProsjekterProjectIdRoute
  NoterArkivIndexRoute: typeof NoterArkivIndexRoute
  NoterProsjekterIndexRoute: typeof NoterProsjekterIndexRoute
  NoterProsjekterProjectIdSceneoppsettRoute: typeof NoterProsjekterProjectIdSceneoppsettRoute
  NoterProsjekterProjectIdSlagverkRoute: typeof NoterProsjekterProjectIdSlagverkRoute
}

const NoterRouteRouteChildren: NoterRouteRouteChildren = {
  NoterIndexRoute: NoterIndexRoute,
  NoterArkivWorkIdRoute: NoterArkivWorkIdRoute,
  NoterProsjekterProjectIdRoute: NoterProsjekterProjectIdRoute,
  NoterArkivIndexRoute: NoterArkivIndexRoute,
  NoterProsjekterIndexRoute: NoterProsjekterIndexRoute,
  NoterProsjekterProjectIdSceneoppsettRoute:
    NoterProsjekterProjectIdSceneoppsettRoute,
  NoterProsjekterProjectIdSlagverkRoute: NoterProsjekterProjectIdSlagverkRoute,
}

const NoterRouteRouteWithChildren = NoterRouteRoute._addFileChildren(
  NoterRouteRouteChildren,
)

interface StyreRouteRouteChildren {
  StyreTaskIdRoute: typeof StyreTaskIdRoute
  StyreIndexRoute: typeof StyreIndexRoute
  StyreMoterMeetingIdRoute: typeof StyreMoterMeetingIdRoute
  StyreProsjekterBoardProjectIdRoute: typeof StyreProsjekterBoardProjectIdRoute
  StyreChatIndexRoute: typeof StyreChatIndexRoute
  StyreDokumenterIndexRoute: typeof StyreDokumenterIndexRoute
  StyreMoterIndexRoute: typeof StyreMoterIndexRoute
  StyreProsjekterIndexRoute: typeof StyreProsjekterIndexRoute
}

const StyreRouteRouteChildren: StyreRouteRouteChildren = {
  StyreTaskIdRoute: StyreTaskIdRoute,
  StyreIndexRoute: StyreIndexRoute,
  StyreMoterMeetingIdRoute: StyreMoterMeetingIdRoute,
  StyreProsjekterBoardProjectIdRoute: StyreProsjekterBoardProjectIdRoute,
  StyreChatIndexRoute: StyreChatIndexRoute,
  StyreDokumenterIndexRoute: StyreDokumenterIndexRoute,
  StyreMoterIndexRoute: StyreMoterIndexRoute,
  StyreProsjekterIndexRoute: StyreProsjekterIndexRoute,
}

const StyreRouteRouteWithChildren = StyreRouteRoute._addFileChildren(
  StyreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GruppeledereRouteRoute: GruppeledereRouteRouteWithChildren,
  NoterRouteRoute: NoterRouteRouteWithChildren,
  StyreRouteRoute: StyreRouteRouteWithChildren,
  GlemtPassordRoute: GlemtPassordRoute,
  LoginRoute: LoginRoute,
  MinProfilRoute: MinProfilRoute,
  TilbakestillPassordRoute: TilbakestillPassordRoute,
  ApiDevLoginRoute: ApiDevLoginRoute,
  ApiDevSeedRoute: ApiDevSeedRoute,
  ArkivWorkIdRoute: ArkivWorkIdRoute,
  BeskjederNyRoute: BeskjederNyRoute,
  InnstillingerNedlastingerRoute: InnstillingerNedlastingerRoute,
  KalenderEventIdRoute: KalenderEventIdRoute,
  MediaMediaIdRoute: MediaMediaIdRoute,
  ProsjekterProjectIdRoute: ProsjekterProjectIdRoute,
  UtstyrAssetIdRoute: UtstyrAssetIdRoute,
  VTokenRoute: VTokenRoute,
  ArkivIndexRoute: ArkivIndexRoute,
  BeskjederIndexRoute: BeskjederIndexRoute,
  InnstillingerIndexRoute: InnstillingerIndexRoute,
  KalenderIndexRoute: KalenderIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  MedlemmerIndexRoute: MedlemmerIndexRoute,
  ProsjekterIndexRoute: ProsjekterIndexRoute,
  UtstyrIndexRoute: UtstyrIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBoardFilesDocumentIdRoute: ApiBoardFilesDocumentIdRoute,
  ApiBoardFilesUploadRoute: ApiBoardFilesUploadRoute,
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
  ApiMediaMediaIdRoute: ApiMediaMediaIdRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiPostImagesImageIdRoute: ApiPostImagesImageIdRoute,
  ApiPostImagesUploadRoute: ApiPostImagesUploadRoute,
  ApiUploadAbortRoute: ApiUploadAbortRoute,
  ApiUploadCompleteRoute: ApiUploadCompleteRoute,
  ApiUploadPartRoute: ApiUploadPartRoute,
  ApiUploadStartRoute: ApiUploadStartRoute,
  ApiUtstyrImagesImageIdRoute: ApiUtstyrImagesImageIdRoute,
  ApiUtstyrImagesUploadRoute: ApiUtstyrImagesUploadRoute,
  BeskjederPostIdRedigerRoute: BeskjederPostIdRedigerRoute,
  KalenderSosialtNyRoute: KalenderSosialtNyRoute,
  BeskjederPostIdIndexRoute: BeskjederPostIdIndexRoute,
  KalenderSosialtIndexRoute: KalenderSosialtIndexRoute,
  KalenderSosialtSocialIdRedigerRoute: KalenderSosialtSocialIdRedigerRoute,
  KalenderSosialtSocialIdIndexRoute: KalenderSosialtSocialIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
