/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlemtPassordRouteImport } from './routes/glemt-passord'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinProfilRouteImport } from './routes/min-profil'
import { Route as NoterRouteRouteImport } from './routes/noter/route'
import { Route as TilbakestillPassordRouteImport } from './routes/tilbakestill-passord'
import { Route as ApiDevLoginRouteImport } from './routes/api/dev-login'
import { Route as ApiDevSeedRouteImport } from './routes/api/dev-seed'
import { Route as ArkivIndexRouteImport } from './routes/arkiv/index'
import { Route as ArkivWorkIdRouteImport } from './routes/arkiv/$workId'
import { Route as InnstillingerIndexRouteImport } from './routes/innstillinger/index'
import { Route as InnstillingerNedlastingerRouteImport } from './routes/innstillinger/nedlastinger'
import { Route as KalenderIndexRouteImport } from './routes/kalender/index'
import { Route as MedlemmerIndexRouteImport } from './routes/medlemmer/index'
import { Route as NoterIndexRouteImport } from './routes/noter/index'
import { Route as ProsjekterIndexRouteImport } from './routes/prosjekter/index'
import { Route as ProsjekterProjectIdRouteImport } from './routes/prosjekter/$projectId'
import { Route as VTokenRouteImport } from './routes/v/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesFileIdRouteImport } from './routes/api/files/$fileId'
import { Route as ApiUploadAbortRouteImport } from './routes/api/upload/abort'
import { Route as ApiUploadCompleteRouteImport } from './routes/api/upload/complete'
import { Route as ApiUploadPartRouteImport } from './routes/api/upload/part'
import { Route as ApiUploadStartRouteImport } from './routes/api/upload/start'
import { Route as NoterArkivIndexRouteImport } from './routes/noter/arkiv/index'
import { Route as NoterArkivWorkIdRouteImport } from './routes/noter/arkiv/$workId'
import { Route as NoterProsjekterIndexRouteImport } from './routes/noter/prosjekter/index'
import { Route as NoterProsjekterProjectIdRouteImport } from './routes/noter/prosjekter/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlemtPassordRoute = GlemtPassordRouteImport.update({
  id: '/glemt-passord',
  path: '/glemt-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinProfilRoute = MinProfilRouteImport.update({
  id: '/min-profil',
  path: '/min-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NoterRouteRoute = NoterRouteRouteImport.update({
  id: '/noter',
  path: '/noter',
  getParentRoute: () => rootRouteImport,
} as any)
const TilbakestillPassordRoute = TilbakestillPassordRouteImport.update({
  id: '/tilbakestill-passord',
  path: '/tilbakestill-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLoginRoute = ApiDevLoginRouteImport.update({
  id: '/api/dev-login',
  path: '/api/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSeedRoute = ApiDevSeedRouteImport.update({
  id: '/api/dev-seed',
  path: '/api/dev-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivIndexRoute = ArkivIndexRouteImport.update({
  id: '/arkiv/',
  path: '/arkiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivWorkIdRoute = ArkivWorkIdRouteImport.update({
  id: '/arkiv/$workId',
  path: '/arkiv/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const InnstillingerIndexRoute = InnstillingerIndexRouteImport.update({
  id: '/innstillinger/',
  path: '/innstillinger/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnstillingerNedlastingerRoute =
  InnstillingerNedlastingerRouteImport.update({
    id: '/innstillinger/nedlastinger',
    path: '/innstillinger/nedlastinger',
    getParentRoute: () => rootRouteImport,
  } as any)
const KalenderIndexRoute = KalenderIndexRouteImport.update({
  id: '/kalender/',
  path: '/kalender/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedlemmerIndexRoute = MedlemmerIndexRouteImport.update({
  id: '/medlemmer/',
  path: '/medlemmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoterIndexRoute = NoterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoterRouteRoute,
} as any)
const ProsjekterIndexRoute = ProsjekterIndexRouteImport.update({
  id: '/prosjekter/',
  path: '/prosjekter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjekterProjectIdRoute = ProsjekterProjectIdRouteImport.update({
  id: '/prosjekter/$projectId',
  path: '/prosjekter/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/api/files/$fileId',
  path: '/api/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadAbortRoute = ApiUploadAbortRouteImport.update({
  id: '/api/upload/abort',
  path: '/api/upload/abort',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCompleteRoute = ApiUploadCompleteRouteImport.update({
  id: '/api/upload/complete',
  path: '/api/upload/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPartRoute = ApiUploadPartRouteImport.update({
  id: '/api/upload/part',
  path: '/api/upload/part',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadStartRoute = ApiUploadStartRouteImport.update({
  id: '/api/upload/start',
  path: '/api/upload/start',
  getParentRoute: () => rootRouteImport,
} as any)
const NoterArkivIndexRoute = NoterArkivIndexRouteImport.update({
  id: '/arkiv/',
  path: '/arkiv/',
  getParentRoute: () => NoterRouteRoute,
} as any)
const NoterArkivWorkIdRoute = NoterArkivWorkIdRouteImport.update({
  id: '/arkiv/$workId',
  path: '/arkiv/$workId',
  getParentRoute: () => NoterRouteRoute,
} as any)
const NoterProsjekterIndexRoute = NoterProsjekterIndexRouteImport.update({
  id: '/prosjekter/',
  path: '/prosjekter/',
  getParentRoute: () => NoterRouteRoute,
} as any)
const NoterProsjekterProjectIdRoute =
  NoterProsjekterProjectIdRouteImport.update({
    id: '/prosjekter/$projectId',
    path: '/prosjekter/$projectId',
    getParentRoute: () => NoterRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noter': typeof NoterRouteRouteWithChildren
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/min-profil': typeof MinProfilRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/innstillinger/nedlastinger': typeof InnstillingerNedlastingerRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/innstillinger/': typeof InnstillingerIndexRoute
  '/kalender/': typeof KalenderIndexRoute
  '/medlemmer/': typeof MedlemmerIndexRoute
  '/noter/': typeof NoterIndexRoute
  '/prosjekter/': typeof ProsjekterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/upload/abort': typeof ApiUploadAbortRoute
  '/api/upload/complete': typeof ApiUploadCompleteRoute
  '/api/upload/part': typeof ApiUploadPartRoute
  '/api/upload/start': typeof ApiUploadStartRoute
  '/noter/arkiv/$workId': typeof NoterArkivWorkIdRoute
  '/noter/prosjekter/$projectId': typeof NoterProsjekterProjectIdRoute
  '/noter/arkiv/': typeof NoterArkivIndexRoute
  '/noter/prosjekter/': typeof NoterProsjekterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/min-profil': typeof MinProfilRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/innstillinger/nedlastinger': typeof InnstillingerNedlastingerRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv': typeof ArkivIndexRoute
  '/innstillinger': typeof InnstillingerIndexRoute
  '/kalender': typeof KalenderIndexRoute
  '/medlemmer': typeof MedlemmerIndexRoute
  '/noter': typeof NoterIndexRoute
  '/prosjekter': typeof ProsjekterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/upload/abort': typeof ApiUploadAbortRoute
  '/api/upload/complete': typeof ApiUploadCompleteRoute
  '/api/upload/part': typeof ApiUploadPartRoute
  '/api/upload/start': typeof ApiUploadStartRoute
  '/noter/arkiv/$workId': typeof NoterArkivWorkIdRoute
  '/noter/prosjekter/$projectId': typeof NoterProsjekterProjectIdRoute
  '/noter/arkiv': typeof NoterArkivIndexRoute
  '/noter/prosjekter': typeof NoterProsjekterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noter': typeof NoterRouteRouteWithChildren
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/min-profil': typeof MinProfilRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/dev-seed': typeof ApiDevSeedRoute
  '/arkiv/$workId': typeof ArkivWorkIdRoute
  '/innstillinger/nedlastinger': typeof InnstillingerNedlastingerRoute
  '/prosjekter/$projectId': typeof ProsjekterProjectIdRoute
  '/v/$token': typeof VTokenRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/innstillinger/': typeof InnstillingerIndexRoute
  '/kalender/': typeof KalenderIndexRoute
  '/medlemmer/': typeof MedlemmerIndexRoute
  '/noter/': typeof NoterIndexRoute
  '/prosjekter/': typeof ProsjekterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/api/upload/abort': typeof ApiUploadAbortRoute
  '/api/upload/complete': typeof ApiUploadCompleteRoute
  '/api/upload/part': typeof ApiUploadPartRoute
  '/api/upload/start': typeof ApiUploadStartRoute
  '/noter/arkiv/$workId': typeof NoterArkivWorkIdRoute
  '/noter/prosjekter/$projectId': typeof NoterProsjekterProjectIdRoute
  '/noter/arkiv/': typeof NoterArkivIndexRoute
  '/noter/prosjekter/': typeof NoterProsjekterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/noter'
    | '/glemt-passord'
    | '/login'
    | '/min-profil'
    | '/tilbakestill-passord'
    | '/api/dev-login'
    | '/api/dev-seed'
    | '/arkiv/$workId'
    | '/innstillinger/nedlastinger'
    | '/prosjekter/$projectId'
    | '/v/$token'
    | '/arkiv/'
    | '/innstillinger/'
    | '/kalender/'
    | '/medlemmer/'
    | '/noter/'
    | '/prosjekter/'
    | '/api/auth/$'
    | '/api/files/$fileId'
    | '/api/upload/abort'
    | '/api/upload/complete'
    | '/api/upload/part'
    | '/api/upload/start'
    | '/noter/arkiv/$workId'
    | '/noter/prosjekter/$projectId'
    | '/noter/arkiv/'
    | '/noter/prosjekter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glemt-passord'
    | '/login'
    | '/min-profil'
    | '/tilbakestill-passord'
    | '/api/dev-login'
    | '/api/dev-seed'
    | '/arkiv/$workId'
    | '/innstillinger/nedlastinger'
    | '/prosjekter/$projectId'
    | '/v/$token'
    | '/arkiv'
    | '/innstillinger'
    | '/kalender'
    | '/medlemmer'
    | '/noter'
    | '/prosjekter'
    | '/api/auth/$'
    | '/api/files/$fileId'
    | '/api/upload/abort'
    | '/api/upload/complete'
    | '/api/upload/part'
    | '/api/upload/start'
    | '/noter/arkiv/$workId'
    | '/noter/prosjekter/$projectId'
    | '/noter/arkiv'
    | '/noter/prosjekter'
  id:
    | '__root__'
    | '/'
    | '/noter'
    | '/glemt-passord'
    | '/login'
    | '/min-profil'
    | '/tilbakestill-passord'
    | '/api/dev-login'
    | '/api/dev-seed'
    | '/arkiv/$workId'
    | '/innstillinger/nedlastinger'
    | '/prosjekter/$projectId'
    | '/v/$token'
    | '/arkiv/'
    | '/innstillinger/'
    | '/kalender/'
    | '/medlemmer/'
    | '/noter/'
    | '/prosjekter/'
    | '/api/auth/$'
    | '/api/files/$fileId'
    | '/api/upload/abort'
    | '/api/upload/complete'
    | '/api/upload/part'
    | '/api/upload/start'
    | '/noter/arkiv/$workId'
    | '/noter/prosjekter/$projectId'
    | '/noter/arkiv/'
    | '/noter/prosjekter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoterRouteRoute: typeof NoterRouteRouteWithChildren
  GlemtPassordRoute: typeof GlemtPassordRoute
  LoginRoute: typeof LoginRoute
  MinProfilRoute: typeof MinProfilRoute
  TilbakestillPassordRoute: typeof TilbakestillPassordRoute
  ApiDevLoginRoute: typeof ApiDevLoginRoute
  ApiDevSeedRoute: typeof ApiDevSeedRoute
  ArkivWorkIdRoute: typeof ArkivWorkIdRoute
  InnstillingerNedlastingerRoute: typeof InnstillingerNedlastingerRoute
  ProsjekterProjectIdRoute: typeof ProsjekterProjectIdRoute
  VTokenRoute: typeof VTokenRoute
  ArkivIndexRoute: typeof ArkivIndexRoute
  InnstillingerIndexRoute: typeof InnstillingerIndexRoute
  KalenderIndexRoute: typeof KalenderIndexRoute
  MedlemmerIndexRoute: typeof MedlemmerIndexRoute
  ProsjekterIndexRoute: typeof ProsjekterIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
  ApiUploadAbortRoute: typeof ApiUploadAbortRoute
  ApiUploadCompleteRoute: typeof ApiUploadCompleteRoute
  ApiUploadPartRoute: typeof ApiUploadPartRoute
  ApiUploadStartRoute: typeof ApiUploadStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glemt-passord': {
      id: '/glemt-passord'
      path: '/glemt-passord'
      fullPath: '/glemt-passord'
      preLoaderRoute: typeof GlemtPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/min-profil': {
      id: '/min-profil'
      path: '/min-profil'
      fullPath: '/min-profil'
      preLoaderRoute: typeof MinProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter': {
      id: '/noter'
      path: '/noter'
      fullPath: '/noter'
      preLoaderRoute: typeof NoterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilbakestill-passord': {
      id: '/tilbakestill-passord'
      path: '/tilbakestill-passord'
      fullPath: '/tilbakestill-passord'
      preLoaderRoute: typeof TilbakestillPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-login': {
      id: '/api/dev-login'
      path: '/api/dev-login'
      fullPath: '/api/dev-login'
      preLoaderRoute: typeof ApiDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-seed': {
      id: '/api/dev-seed'
      path: '/api/dev-seed'
      fullPath: '/api/dev-seed'
      preLoaderRoute: typeof ApiDevSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/': {
      id: '/arkiv/'
      path: '/arkiv'
      fullPath: '/arkiv/'
      preLoaderRoute: typeof ArkivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/$workId': {
      id: '/arkiv/$workId'
      path: '/arkiv/$workId'
      fullPath: '/arkiv/$workId'
      preLoaderRoute: typeof ArkivWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innstillinger/': {
      id: '/innstillinger/'
      path: '/innstillinger'
      fullPath: '/innstillinger/'
      preLoaderRoute: typeof InnstillingerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innstillinger/nedlastinger': {
      id: '/innstillinger/nedlastinger'
      path: '/innstillinger/nedlastinger'
      fullPath: '/innstillinger/nedlastinger'
      preLoaderRoute: typeof InnstillingerNedlastingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender/': {
      id: '/kalender/'
      path: '/kalender'
      fullPath: '/kalender/'
      preLoaderRoute: typeof KalenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medlemmer/': {
      id: '/medlemmer/'
      path: '/medlemmer'
      fullPath: '/medlemmer/'
      preLoaderRoute: typeof MedlemmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter/': {
      id: '/noter/'
      path: '/'
      fullPath: '/noter/'
      preLoaderRoute: typeof NoterIndexRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/prosjekter/': {
      id: '/prosjekter/'
      path: '/prosjekter'
      fullPath: '/prosjekter/'
      preLoaderRoute: typeof ProsjekterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekter/$projectId': {
      id: '/prosjekter/$projectId'
      path: '/prosjekter/$projectId'
      fullPath: '/prosjekter/$projectId'
      preLoaderRoute: typeof ProsjekterProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/api/files/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/abort': {
      id: '/api/upload/abort'
      path: '/api/upload/abort'
      fullPath: '/api/upload/abort'
      preLoaderRoute: typeof ApiUploadAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/complete': {
      id: '/api/upload/complete'
      path: '/api/upload/complete'
      fullPath: '/api/upload/complete'
      preLoaderRoute: typeof ApiUploadCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/part': {
      id: '/api/upload/part'
      path: '/api/upload/part'
      fullPath: '/api/upload/part'
      preLoaderRoute: typeof ApiUploadPartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/start': {
      id: '/api/upload/start'
      path: '/api/upload/start'
      fullPath: '/api/upload/start'
      preLoaderRoute: typeof ApiUploadStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter/arkiv/': {
      id: '/noter/arkiv/'
      path: '/arkiv'
      fullPath: '/noter/arkiv/'
      preLoaderRoute: typeof NoterArkivIndexRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/noter/arkiv/$workId': {
      id: '/noter/arkiv/$workId'
      path: '/arkiv/$workId'
      fullPath: '/noter/arkiv/$workId'
      preLoaderRoute: typeof NoterArkivWorkIdRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/noter/prosjekter/': {
      id: '/noter/prosjekter/'
      path: '/prosjekter'
      fullPath: '/noter/prosjekter/'
      preLoaderRoute: typeof NoterProsjekterIndexRouteImport
      parentRoute: typeof NoterRouteRoute
    }
    '/noter/prosjekter/$projectId': {
      id: '/noter/prosjekter/$projectId'
      path: '/prosjekter/$projectId'
      fullPath: '/noter/prosjekter/$projectId'
      preLoaderRoute: typeof NoterProsjekterProjectIdRouteImport
      parentRoute: typeof NoterRouteRoute
    }
  }
}

interface NoterRouteRouteChildren {
  NoterIndexRoute: typeof NoterIndexRoute
  NoterArkivWorkIdRoute: typeof NoterArkivWorkIdRoute
  NoterProsjekterProjectIdRoute: typeof NoterProsjekterProjectIdRoute
  NoterArkivIndexRoute: typeof NoterArkivIndexRoute
  NoterProsjekterIndexRoute: typeof NoterProsjekterIndexRoute
}

const NoterRouteRouteChildren: NoterRouteRouteChildren = {
  NoterIndexRoute: NoterIndexRoute,
  NoterArkivWorkIdRoute: NoterArkivWorkIdRoute,
  NoterProsjekterProjectIdRoute: NoterProsjekterProjectIdRoute,
  NoterArkivIndexRoute: NoterArkivIndexRoute,
  NoterProsjekterIndexRoute: NoterProsjekterIndexRoute,
}

const NoterRouteRouteWithChildren = NoterRouteRoute._addFileChildren(
  NoterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoterRouteRoute: NoterRouteRouteWithChildren,
  GlemtPassordRoute: GlemtPassordRoute,
  LoginRoute: LoginRoute,
  MinProfilRoute: MinProfilRoute,
  TilbakestillPassordRoute: TilbakestillPassordRoute,
  ApiDevLoginRoute: ApiDevLoginRoute,
  ApiDevSeedRoute: ApiDevSeedRoute,
  ArkivWorkIdRoute: ArkivWorkIdRoute,
  InnstillingerNedlastingerRoute: InnstillingerNedlastingerRoute,
  ProsjekterProjectIdRoute: ProsjekterProjectIdRoute,
  VTokenRoute: VTokenRoute,
  ArkivIndexRoute: ArkivIndexRoute,
  InnstillingerIndexRoute: InnstillingerIndexRoute,
  KalenderIndexRoute: KalenderIndexRoute,
  MedlemmerIndexRoute: MedlemmerIndexRoute,
  ProsjekterIndexRoute: ProsjekterIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
  ApiUploadAbortRoute: ApiUploadAbortRoute,
  ApiUploadCompleteRoute: ApiUploadCompleteRoute,
  ApiUploadPartRoute: ApiUploadPartRoute,
  ApiUploadStartRoute: ApiUploadStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
